pipeline{
    agent any

    stages{
        stage('init'){
            steps{
                sh 'terraform init -on-color'
            }
        }
          
                stage('format'){
            steps{
                sh 'terraform fmt -on-color'
            }
        }
        
           stage('plan'){
            steps{
                sh 'terraform plan -on-color'
            }
        }


    }
}